trigger:
  branches:
    include:
      - main

variables:
  acrName: 'myacrramraja'
  imageName: 'rambeginerdoaks'

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: DockerBuild
    displayName: Build & Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        repository: '$(imageName)'
        dockerfile: '**/Dockerfile'
        containerRegistry: 'acr-connection'  # 👉 ACR service connection name
        tags: |
          latest

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: BuildAndPush
  jobs:
  - job: kubectlDeploy
    displayName: Deploy to AKS Cluster
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'aks-service-connection'  # 👉 Azure DevOps service connection name
        azureResourceGroup: 'FP'
        kubernetesCluster: 'aks-raja-cluster'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'deployment.yaml\nservice.yaml'
